
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--fix"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.schema]
command = "cargo"
args = ["schema"]
dependencies = ["build"]

[tasks.git_flow]
dependencies = [
  "format",
  "build",
  "test",
  "schema"
]

[tasks.git_flow_commited]
dependencies = [
  "git_flow",
  "clippy"
]
